'use strict';
const D=window.MYOPIA_DATA,C=window.MYOPIA_CONTENT;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,title,cls='source-link')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`;
const sourcesById=Object.fromEntries(C.sources.map(s=>[s.id,s]));
const cites=item=>(item.sourceLinks||item.sourceIds?.map(id=>sourcesById[id])||[{title:item.sourceTitle,url:item.sourceUrl}]).filter(s=>s?.url).map(s=>link(s.url,s.title,'inline-source')).join(' · ');
const records=D.records.flatMap(r=>{const base={...r,indicator:r.indicator||'近視'};return r.highMyopia?[base,{...r,id:r.id+'-high',indicator:'高度近視',prevalence:r.highMyopia.prevalence,ci:r.highMyopia.ci,definition:r.highMyopia.definition,highMyopia:null}]:[base]}).sort((a,b)=>parseInt(a.studyYear)-parseInt(b.studyYear));
const timeline=[['1996–2000','從學校與社區開始','不同國家展開屈光調查，樣本、年齡與驗光方法決定數字意義。'],['2001–2010','看見地區差異','亞洲、非洲、美洲與大洋洲的研究提醒我們：不能把單一城市當成全國。'],['2011–2015','把介入帶進校園','廣州戶外活動試驗，追蹤原本未近視的兒童，研究新發近視能否減少。'],['2016–2020','模型與追蹤並進','全球模型提供長期情境；台灣調查則提供特定年齡的實測時間對照。'],['2021–2025','繼續追問證據','2024 系統性綜述整理戶外介入研究；仍沒有每國每年、同方法的完整序列。']];
$('#timeline').innerHTML=timeline.map(([y,t,p])=>`<article><strong>${y}</strong><h3>${t}</h3><p>${p}</p></article>`).join('');
for(const country of [...new Set(records.map(r=>r.country))])$('#country').insertAdjacentHTML('beforeend',`<option value="${esc(country)}">${esc(country)}</option>`);
let chartMode='prevalence';
function renderChart(){const model=D.globalModel.filter(m=>m.year<=2025||$('#projection').checked);const isPop=chartMode==='population';const max=isPop?6000:60;const val=m=>isPop?m.countMillion:m.myopia;const high=m=>isPop?m.highCountMillion:m.highMyopia;const fmt=v=>isPop?(v/1000).toFixed(2)+' 十億':v.toFixed(1)+'%';
$('#global-chart').innerHTML=`<div class="chart-unit">${isPop?'人口數（十億人）':'占全球所有年齡人口（%）'} · 同一模型的代表年份</div><div class="bar-plot"><div class="chart-ticks">${[max,max*2/3,max/3,0].map(v=>`<span>${isPop?v/1000:v}%REPLACE%</span>`.replace('%REPLACE%',isPop?'':'%')).join('')}</div><div class="bar-groups">${model.map(m=>`<div class="bar-group ${m.year>2025?'future':''}"><div class="bars"><div class="bar myopia-bar" style="height:${val(m)/max*100}%"><span>${fmt(val(m))}</span></div><div class="bar high-bar" style="height:${high(m)/max*100}%"><span>${fmt(high(m))}</span></div></div><strong>${m.year}</strong><small>${m.year>2025?'未來預測':m.year>=2020?'當時的預測':'模型估算'}</small></div>`).join('')}</div></div>`;
$('#model-table').innerHTML='<caption>模型原文點估計與不確定區間（摘要／圖標示 95% CI）；人數單位：百萬人</caption><thead><tr><th scope="col">年份／性質</th><th scope="col">近視 %（95% CI）</th><th scope="col">近視人口（95% CI）</th><th scope="col">高度近視 %（95% CI）</th><th scope="col">高度近視人口（95% CI）</th></tr></thead><tbody>'+model.map(m=>`<tr><th scope="row">${m.year}<br>${m.year>2025?'未來預測':m.year>=2020?'當時的預測':'模型估算'}</th><td>${m.myopia}%<br>${esc(m.ci)}</td><td>${m.countMillion}<br>${esc(m.countCiMillion)}</td><td>${m.highMyopia}%<br>${esc(m.highCi)}</td><td>${m.highCountMillion}<br>${esc(m.highCountCiMillion)}</td></tr>`).join('')+'</tbody>';
}
$$('[data-chart]').forEach(b=>b.addEventListener('click',()=>{chartMode=b.dataset.chart;$$('[data-chart]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b?'true':'false')});renderChart()}));$('#projection').addEventListener('change',renderChart);
function renderRecords(){const query=$('#search').value.trim().toLocaleLowerCase();const found=records.filter(r=>($('#country').value==='all'||r.country===$('#country').value)&&($('#age').value==='all'||r.ageGroup===$('#age').value)&&($('#indicator').value==='all'||r.indicator===$('#indicator').value)&&(!query||JSON.stringify(r).toLocaleLowerCase().includes(query)));
$('#result-count').textContent=`${found.length} 筆指標紀錄 · ${new Set(found.map(r=>r.country)).size} 個國家／地區`;$('#empty').hidden=found.length>0;
$('#records').innerHTML=found.map(r=>`<article class="record"><div class="record-header"><h3>${esc(r.country)}</h3><span class="sample-badge">${r.ageGroup==='child'?'兒童／青少年':r.ageGroup==='young-adult'?'年輕成人':'成人'}</span></div><p class="place">${esc(r.region)}</p><div class="stat">${r.prevalence}<span>%</span></div><div class="stat-label">${esc(r.indicator)}盛行率 · ${esc(r.age)}</div><p class="uncertainty">${esc(r.ci)}</p><dl><dt>調查年</dt><dd>${esc(r.studyYear)}</dd><dt>發表年</dt><dd>${r.publicationYear}</dd><dt>定義</dt><dd>${esc(r.definition)}</dd><dt>驗光</dt><dd>${esc(r.cycloplegia.split('；')[0])}</dd></dl><p class="caution">${esc(r.limitations)}</p><details><summary>展開樣本、方法與來源</summary><p><b>分母：</b>${esc(r.denominator)}</p><p><b>抽樣：</b>${esc(r.sampling)}</p><p><b>方法：</b>${esc(r.method)}</p>${link(r.sourceUrl,r.sourceTitle)}${(r.additionalSources||[]).map(s=>'<br>'+link(s.url,s.title)).join('')}<p>查核：2026-10-07</p></details></article>`).join('');
$('#records-table').innerHTML='<caption>代表性實測研究；不可直接跨研究排名</caption><thead><tr><th scope="col">國家／地區</th><th scope="col">調查年／發表年</th><th scope="col">年齡／分母</th><th scope="col">指標／比例／區間</th><th scope="col">定義／驗光</th><th scope="col">來源與限制</th></tr></thead><tbody>'+found.map(r=>`<tr><th scope="row">${esc(r.country)}<br>${esc(r.region)}</th><td>${esc(r.studyYear)}<br>發表 ${r.publicationYear}</td><td>${esc(r.age)}<br>${esc(r.denominator)}</td><td>${esc(r.indicator)} ${r.prevalence}%<br>${esc(r.ci)}</td><td>${esc(r.definition)}<br>${esc(r.cycloplegia.split('；')[0])}</td><td>${link(r.sourceUrl,r.sourceTitle)}<br>${esc(r.limitations)}</td></tr>`).join('')+'</tbody>';
}
['search','country','age','indicator'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderRecords));$('#reset').addEventListener('click',()=>{$('#search').value='';['country','age','indicator'].forEach(id=>$('#'+id).value='all');renderRecords();$('#search').focus()});
$('#concepts').innerHTML=C.concept.map(x=>`<article class="concept-item"><h3>${esc(x.title)}</h3><p>${esc(x.text)}<br>${cites(x)}</p></article>`).join('');
$('#health-list').innerHTML=C.health.map((x,i)=>`<article class="health"><span class="health-number">0${i+1} / EVERYDAY CARE</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p>${cites(x)}</article>`).join('');
$('#urgent').innerHTML=esc(C.urgentNotice.text)+'<br>'+cites(C.urgentNotice);
$('#myths').innerHTML=C.myths.map(x=>`<details><summary>${esc(x.title)}</summary><p><strong>${esc(x.verdict)}。</strong>${esc(x.text)}<br>${cites(x)}</p></details>`).join('');
$('#case-list').innerHTML=C.cases.map((x,i)=>`<article class="case"><span class="case-no">0${i+1}</span><div><p class="eyebrow">${esc(x.place)} / ${esc(x.publishedYear)} 年發表</p><h3>${esc(x.title)}</h3><span class="case-type">${esc(x.type)}</span><p>${esc(x.intervention)}</p><p>${esc(x.takeaway)}</p></div><div><p class="outcome">${esc(x.result)}</p><p>${esc(x.limitation)}</p><details><summary>這項證據是怎麼得到的？</summary><p><b>研究期間：</b>${esc(x.studyPeriod)}</p><p><b>年齡與分母：</b>${esc(x.participants)}</p><p><b>方法與定義：</b>${esc(x.measurement)}</p></details>${cites(x)}${(x.sourceIds||[]).map(id=>sourcesById[id]).filter(s=>s?.fullTextUrl).map(s=>'<br>'+link(s.fullTextUrl,'完整論文')).join('')}</div></article>`).join('');
$('#teacher').innerHTML=C.teacher.map(x=>`<article><h4>${esc(x.title)}</h4><p>${esc(x.text)}</p></article>`).join('');
let qi=0,score=0,answered=false;const quiz=[{question:'2050 年全球近視預測，是已經測量完成的人口普查結果。',answer:false,explanation:'2050 是未來情境，取決於模型資料與假設，不能當成已發生事實。',sourceUrl:'https://doi.org/10.1016/j.ophtha.2016.01.006',sourceTitle:'Holden et al., 2016'},...C.quiz];
function renderQuiz(){answered=false;$('#quiz-feedback').innerHTML='';$('#quiz-next').hidden=true;$('#quiz-progress').textContent=`${qi+1} / ${quiz.length}`;$('#quiz').innerHTML=`<h3 class="quiz-question">${esc(quiz[qi].question)}</h3><div class="quiz-options"><button type="button" data-answer="true">我認為：正確</button><button type="button" data-answer="false">我認為：不正確</button></div>`;$$('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=(b.dataset.answer==='true')===quiz[qi].answer;if(correct)score++;$$('[data-answer]').forEach(x=>{x.disabled=true;if((x.dataset.answer==='true')===quiz[qi].answer)x.classList.add('correct');else if(x===b)x.classList.add('incorrect')});$('#quiz-feedback').innerHTML=`<strong>${correct?'答對了。':'再想一步。'}</strong> ${esc(quiz[qi].explanation)}<br>${cites(quiz[qi])}`;$('#quiz-next').hidden=false;$('#quiz-next').textContent=qi===quiz.length-1?'看學習結果 →':'下一題 →'}))}
$('#quiz-next').addEventListener('click',()=>{if(!answered)return;if(qi<quiz.length-1){qi++;renderQuiz()}else{$('#quiz-progress').textContent='完成';$('#quiz').innerHTML=`<h3 class="quiz-question">你答對 ${score} / ${quiz.length} 題</h3><p>真正的收穫：讀數字之前，先問「誰、何時、怎麼量」。</p><button type="button" id="quiz-restart" class="button">再挑戰一次 ↺</button>`;$('#quiz-feedback').innerHTML='';$('#quiz-next').hidden=true;$('#quiz-restart').addEventListener('click',()=>{qi=0;score=0;renderQuiz()})}});
$('#evidence-limits').innerHTML=C.evidenceLimits.map(x=>`<article class="evidence-note"><h3>${esc(x.title)}</h3><p>${esc(x.text)}<br>${cites(x)}</p></article>`).join('');
const sourceMap=new Map;[...C.sources,...D.records.flatMap(r=>r.additionalSources||[]),...D.records.map(r=>({title:r.sourceTitle,url:r.sourceUrl,year:r.publicationYear,type:'原始調查研究'})),{title:'Holden et al.｜Global Prevalence of Myopia and High Myopia and Temporal Trends from 2000 through 2050',url:'https://doi.org/10.1016/j.ophtha.2016.01.006',year:2016,type:'系統綜述與全球模型'}].forEach(s=>{if(!sourceMap.has(s.url))sourceMap.set(s.url,s)});
$('#sources').innerHTML=[...sourceMap.values()].map(s=>`<li>${link(s.url,s.title)}<span>${esc(s.publisher||s.type||'來源')} ${s.year?'· '+s.year+' 年發表':''} · 查核 2026-10-07</span></li>`).join('');
$('#model-method').innerHTML=`<p>Holden 等人整合 145 項研究、210 萬名受試者的資料，以各地年齡別盛行率與人口估計建立全球模型；分母為對應年份全球所有年齡人口，而不是 210 萬名樣本。近視：球面等效屈光度 ≤ −0.50 D；高度近視：≤ −5.00 D（不同於 IMI 常用的 ≤ −6.00 D）。原始研究測量與散瞳方式不一致，模型調整不能消除全部差異。全球人數不是將本網站幾筆國家樣本直接加總。</p><p>原文內部差異：2020 年近視比例正文為 34.0%，Table 1 為 33.9%；本站採正文。2050 年高度近視人數上界正文為 2,105 百萬、摘要為 2,104 百萬；本站採正文。原文正文稱「不確定區間」，摘要與圖稱「95% CI」；模型也納入人口預估的不確定性。所有區間照來源呈現，不自行增加精確度。</p>${link('https://doi.org/10.1016/j.ophtha.2016.01.006','Holden et al., Ophthalmology (2016)')}`;
const tw=D.records.filter(r=>/台灣|臺灣/.test(r.country));$('#taiwan-content').innerHTML=tw.length>=2?`<p>同為 12 歲、同一台灣全國調查系列：${tw[0].studyYear} 年近視盛行率 ${tw[0].prevalence}%（${esc(tw[0].ci)}），${tw[1].studyYear} 年為 ${tw[1].prevalence}%（${esc(tw[1].ci)}）。這比拿不同國家、不同年齡的數字硬比更有意義。</p><p>但這仍是不同年度的橫斷面樣本，不是追蹤同一批兒童；也不等於所有台灣人的比例。此系列用 ≤ −0.25 D 門檻，與其他研究的 ≤ −0.50 D 不同。不能直接外推全台近視人口數。</p>${link(tw[0].sourceUrl,tw[0].sourceTitle)}`:'<p>比較台灣與其他地區前，先確認年齡、年份、抽樣方式與近視定義是否相同。</p>';
function printGuide(){document.body.classList.add('printing');window.print()}$('#print').addEventListener('click',printGuide);$('#print2').addEventListener('click',printGuide);window.addEventListener('afterprint',()=>document.body.classList.remove('printing'));
renderChart();renderRecords();renderQuiz();
