const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const window={addEventListener(){},print(){window.printed=true}};vm.runInNewContext(fs.readFileSync(__dirname+'/data.js','utf8'),{window});const {MYOPIA_DATA:D,MYOPIA_CONTENT:C}=window;let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++};
ok(D.records.length===12,'12 original geographic records');const seen=new Set;for(const r of D.records){for(const k of ['id','country','region','studyYear','publicationYear','age','ageGroup','indicator','prevalence','ci','denominator','sampling','definition','cycloplegia','method','limitations','sourceTitle','sourceUrl'])ok(r[k]!==undefined&&r[k]!=='',`${r.id}.${k}`);ok(!seen.has(r.id),'unique id');seen.add(r.id);ok(r.prevalence>=0&&r.prevalence<=100,'valid prevalence');ok(r.publicationYear<=2025,'historical publication cutoff');ok(r.sourceUrl.startsWith('https://'),'source HTTPS');if(r.highMyopia){ok(r.highMyopia.prevalence<=r.prevalence,'high subset');ok(r.highMyopia.definition&&r.highMyopia.ci,'high metadata')}}
ok(D.globalModel.map(x=>x.year).join(',')==='2000,2010,2020,2050','sparse, unfilled model');for(const m of D.globalModel){ok(m.myopia>m.highMyopia,'model subset');for(const k of ['ci','highCi','countCiMillion','highCountCiMillion'])ok(m[k],'model uncertainty')};ok(D.globalModel[2].myopia===34,'2020正文');ok(C.cases.length===3,'three case types');for(const s of C.sources)ok(s.url.startsWith('https://'),'content sources');for(const key of ['concept','health','myths','cases','quiz','teacher'])for(const x of C[key])ok(x.sourceUrl||x.sourceIds?.length,`${key} citation`);
const html=fs.readFileSync(__dirname+'/index.html','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);ok(ids.length===new Set(ids).size,'unique HTML ids');for(const [,id]of html.matchAll(/href="#([^"]+)"/g))ok(ids.includes(id),'anchor '+id);for(const [,src]of html.matchAll(/(?:src|href)="([^"#]+\.(?:js|css|svg))"/g))ok(fs.existsSync(__dirname+'/'+src),'asset '+src);
class Node{constructor(){this.innerHTML='';this.textContent='';this.value='';this.hidden=false;this.checked=false;this.handlers={};this.dataset={};this.classes=new Set;this.classList={toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c),add:c=>this.classes.add(c),remove:c=>this.classes.delete(c)};}addEventListener(k,f){this.handlers[k]=f}setAttribute(k,v){this[k]=v}insertAdjacentHTML(_,v){this.innerHTML+=v}focus(){this.focused=true}emit(k){this.handlers[k]?.()}}
const nodes=Object.fromEntries(ids.map(id=>['#'+id,new Node]));for(const id of ['country','age','indicator'])nodes['#'+id].value='all';const chartButtons=['prevalence','population'].map(x=>{const n=new Node;n.dataset.chart=x;return n});let answerButtons=[];const quizNode=nodes['#quiz'];let quizHTML='';Object.defineProperty(quizNode,'innerHTML',{get:()=>quizHTML,set:v=>{quizHTML=v;answerButtons=[...v.matchAll(/data-answer="(true|false)"/g)].map(x=>{const n=new Node;n.dataset.answer=x[1];return n});if(v.includes('id="quiz-restart"'))nodes['#quiz-restart']=new Node}});
const document={querySelector:s=>nodes[s],querySelectorAll:s=>s==='[data-chart]'?chartButtons:s==='[data-answer]'?answerButtons:[],body:new Node};vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8'),{window,document,console});
ok(!nodes['#records'].innerHTML.includes('undefined'),'no missing fields rendered');ok(nodes['#result-count'].textContent.includes('19 筆'),'19 indicator cards');ok(!nodes['#global-chart'].innerHTML.includes('2050'),'future default hidden');nodes['#projection'].checked=true;nodes['#projection'].emit('change');ok(nodes['#global-chart'].innerHTML.includes('2050'),'future toggle');chartButtons[1].emit('click');ok(nodes['#global-chart'].innerHTML.includes('4.76 十億'),'population conversion');nodes['#country'].value='台灣';nodes['#country'].emit('change');ok(nodes['#result-count'].textContent.includes('4 筆'),'Taiwan filter');nodes['#indicator'].value='高度近視';nodes['#indicator'].emit('change');ok(nodes['#result-count'].textContent.includes('2 筆'),'combined indicator filter');nodes['#search'].value='zzz-no-match';nodes['#search'].emit('input');ok(!nodes['#empty'].hidden,'empty state');nodes['#reset'].emit('click');ok(nodes['#result-count'].textContent.includes('19 筆'),'reset');for(let i=0;i<7;i++){const q=i===0?false:C.quiz[i-1].answer;answerButtons.find(b=>b.dataset.answer===String(q)).emit('click');answerButtons.find(b=>b.dataset.answer===String(q)).emit('click');ok(!nodes['#quiz-next'].hidden,'next enabled after answer');nodes['#quiz-next'].emit('click')}ok(quizHTML.includes('7 / 7'),'quiz correct score and repeat protection');nodes['#quiz-restart'].emit('click');ok(nodes['#quiz-progress'].textContent==='1 / 7','quiz restart');nodes['#print'].emit('click');ok(window.printed,'print handler');
console.log(JSON.stringify({passed:true,checks,records:D.records.length,countries:new Set(D.records.map(x=>x.country)).size,indicatorRecords:19,quizQuestions:7,scope:'Data/schema, HTML/assets, simulated DOM interaction unit checks; not browser layout'},null,2));
